name: FirstWorkflow
on: workflow_dispatch
jobs:
 first-action:
   runs-on: ubuntu-latest
   steps:
    - name: Print Greeting
      run: | 
          echo "Hello World"
          echo "Hello World2"
  
